### ISSUE TITLE
Request to add license

### ISSUE THREAD

**Issue by kaswani29** [rohinmanvi/GeoLLM#1]
Hi, 

We were considering this work for further exploration but wanted to check if you can add license to the repository.

Thanks
Krishna

**Comment by rohinmanvi** [comment]
Added Apache License 2.0

**Comment by YuanDaoze** [comment]
> Hi,
> 
> We were considering this work for further exploration but wanted to check if you can add license to the repository.
> 
> Thanks Krishna

Hello，I notice that you want use this work for further study.Recently，I also want study this interesting paper.But,when I prepare to evaluate the model,I find that the author does not appear to have been provided the ground truth file(end with .tif) once they measured in the paper.
I'd like to ask you if you're experiencing this problem as well.
Looking forward to your reply!
